### ISSUE TITLE
Temperatursensor DS18b20 und Platine kaufen oder fertigen lassen?

### ISSUE THREAD

**Issue by Triton-KS** [der-pw/hm_stm32_2ch_dimmer#1]
Hallo,
ich bin gerade auf der Suche nache einem weiteren LED Dimmer.
Dabei bin ich auf die Seite oder das Projekt aufmerksam geworden.

Wofür wird oder ist der Temperatursensor DS18b20 auf der Platine?

Wo oder wie kann man die Platine kaufen oder darf man die sich "nachbestellen" z.B. bei jlcpcb
und funktioniert das mit den Patinen-Dateien da?

**Comment by der-pw** [comment]
Hallo,

der DS18b20 überwacht die Temperatur im Gehäuse, sofern die Platine in
einem Gehäuse verbaut ist.
In der CCU kann eingestellt werden, bei welcher Temperatur um wieviel
Prozent abgedimmt werden soll, wenn es doch mal zu heiß wird, einfach um
Last wegzunehmen.
Ist mir bislang aber noch nicht passiert.

Selbstverständlich kannst du dir die Platinen bei JLC nachbestellen.
Einfach den Ordner "gerber" als Zip-File dort hochladen.
Von der V1.5 hab ich leider keine da.
Eben habe ich das Repo nochmal aufgeräumt, dort findest du jetzt auch eine
gerber.zip. Die kannst du jetzt einfach bei JLC hochladen.

Schöne Grüße,
Patrick

Am So., 4. Okt. 2020 um 22:32 Uhr schrieb Triton-KS <
notifications@github.com>:

**Comment by Triton-KS** [comment]
Hallo Patrick,

Danke für deine schnelle Rückmeldung.
Mit dem DS18b20 habe ich mir schon sowas gedacht. Kann man den DS18B20 auch als "normalen" Temperatursensor
in / mit der CCU verwenden?

Den Gerber-Ordner als Zip erstellen, ist mir dann auch wieder eingefallen. Hatte bisher nur einmal Platinen bestellt.
So ok dann muss ich nur noch schauen ob der AT24CS32 typengleich mit dem vom Reichelt ist:
[https://www.reichelt.de/eeprom-32-kb-4096-x-8-25-5-5-v-so-8-st-24c32-mn6-p33376.html?&trstct=pos_0&nbc=1](url) 
benötigt man hier ggf 64 kB oder bring ein Wechsel eher Probleme ?

Letzte Frage gibt es Unterschiede zwischen STM32F103C**B**T6 und STM32F103C**8**T6 oder wenn man den STM32F103C**B**T6 nicht bekommt gibt es eine Alternative?

Schöne Grüße 

Triton-KS / Alex
