### ISSUE TITLE
Memory/EEPROM 64kB oder nur 32kB

### ISSUE THREAD

**Issue by Triton-KS** [der-pw/hm_stm32_2ch_dimmer#3]
Hi,
ist es auch möglich einen EEPROM mit 64kB zu benutzen?
Auf was sollte man hierbei achten?

Danke

**Comment by der-pw** [comment]
Hallo,
kann ich gar nicht genau beantworten.
Wobei 64kB wohl etwas groß sein dürfte, ob aber auch 64k**b** gehen weiß ich nicht. ;-)

Wenn es dir aber nur darum geht, dass der AT24C**S**32 schlecht verfügbar ist, der AT24C32 geht auch.
https://homematic-forum.de/forum/viewtopic.php?f=76&t=44795&sid=dd18714128fa125053a4a61388e723d7&start=10#p627933

**Comment by Triton-KS** [comment]
Hallo, 
Dankeschön. 
Genau den im Forum beschriebenen oder als Link bei Reichelt benannten habe ich bestellt.
Leider muss ich hier nochmal genauer schauen oder herausfinden wo der Pin 1 ist. Es fehlen auf den bestellten EEPROMs der Markierungspunkt. Aber sollte man ja herausfinden. 
Gestatten Sie oder du mir noch die Frage was die Aufgabe vom EEPROM genau ist? Einfach nur um es zu verstehen.
Danke

**Comment by der-pw** [comment]
"du" ist vollkommen in Ordnung.

Im EEPROM werden die Deviceparamter und Peerings gespeichert.
Quasi das was du in der CCU für das jeweilige Gerät konfigurieren kannst.
(achtung gefährliches Halbwissen) Der STM32 besitzt kein internes EEPROM wie bspw. der AT328P, sondern nur Flashspeicher, welcher IMHO weniger Schreibzyklen als eben ein EEPROM verträgt.


Ja, die sind ja witzig bei ST. :-D
Hab mir meine, bei Reichelt bestellten noch nie angeguckt, da ich noch von ein paar AT-Chips zehre, und so oft baue ich den Dimmer jetzt nicht zusammen.

Wenn sich die Ausrichtung des Aufdrucks analog zum Atmel-EEPROM verhält, sollte Pin1 unten links sein.
![IMG_2603](https://user-images.githubusercontent.com/44023915/103222271-62ca2f80-4924-11eb-8de5-e0d61eebfbc8.JPEG)

**Comment by Triton-KS** [comment]
Servus,
scheinbar lernt man noch mehr durch das Bauen. 
ST machen die Kennzeichnung wohl über die Form.
Erkennt man ja auh gut über die Vergrößerung

![st24c32wp_Form](https://user-images.githubusercontent.com/67431210/103282626-ab422580-49d6-11eb-8c84-873d74853cfe.png)

**Comment by der-pw** [comment]
Ah, sehr gut! 
Haben wir wieder was gelernt.

Danke für die Info.
