### ISSUE TITLE
Encoder1/2 Funktion?

### ISSUE THREAD

**Issue by Triton-KS** [der-pw/hm_stm32_2ch_dimmer#4]
Hallo,
die Encoder 1 und Encoder 2 dienen zur externen "Ansteuerung / Helligkeitsveränderung" der angeschlossenen LEDs,
ist das richtig?
Und wenn ja wie steuert man diese dann genau an oder gibt es dafür auch einen Schaltung oder Platine?

**Comment by der-pw** [comment]
Im Prinzip brauchst du nichts weiter als einen Drehencoder.
https://www.amazon.de/RoboMall-Drehencoder-Drehgeber-KY-040-Modul/dp/B00QHEMUQK

Den verbindest du gemäß der Pinbezeichnung auf der Platine, und das Hühnerfutter natürlich nicht vergessen.
In den meisten Sketches sollte das dank pa-pa auch eingebaut sein.
https://github.com/pa-pa/AskSinPP/blob/master/examples/stm32/HM-LC-DW-WM/HM-LC-DW-WM.ino#L74-L75

**Comment by Triton-KS** [comment]
Ohje danke,
was man nicht alles nach ca. 20 Jahren Lehre an Begriffen vergisst oder einfach zu kompliziert Denkt.
Keine Ahnung was ist hier für eine "wilde" Schaltung erwartet hatte. Aber naja wenn man erst wieder anfängt zu "Basteln" oder sind nebenbei mit Platinen zu beschäftigen, hat man halt noch Wissenslücken.

Dankeschön
