### ISSUE TITLE
Teileliste down

### ISSUE THREAD

**Issue by DennisXK** [der-pw/hm_stm32_2ch_dimmer#5]
Hi kannst du die Teileliste neu hochladen, denn die ist down!

**Comment by der-pw** [comment]
https://github.com/der-pw/hm_stm32_2ch_dimmer/blob/master/Kicad/STM32_2CH_Dimmer_Parts.csv
was ist denn mit dieser Liste hier?

**Comment by DennisXK** [comment]
Ok danke. Hätte noch ein paar Fragen...

-kann man für den EPROM auch einen anderen benutzen? Denn den gibt es beim Conrad, RS, Reichelt nicht. Hättest du du ein alternative EMPROM?

-Der DS18B20 wird der auch ausgelesen und von der Homematic Oberfläche angezeigt? Wäre cool wenn das so wäre :D

-J2 und J3: benötigt man für was genau? Denke nicht das die für den Dimmer nötwenig sind 

-U2 welchen Controller genau? STM32 F103C6T6 oder STM32 F103C8T6?
