### ISSUE TITLE
Fragen

### ISSUE THREAD

**Issue by DennisXK** [der-pw/hm_stm32_2ch_dimmer#6]
Habe leider keine Antwort erhalten, deswegen eine neues Issues.

-kann man für den EPROM auch einen anderen benutzen? Denn den gibt es beim Conrad, RS, Reichelt nicht. Hättest du du ein alternative EMPROM?

-Der DS18B20 wird der auch ausgelesen und von der Homematic Oberfläche angezeigt? Wäre cool wenn das so wäre :D

-J2 und J3: benötigt man für was genau? Denke nicht das die für den Dimmer nötwenig sind

-U2 welchen Controller genau? STM32 F103C6T6 oder STM32 F103C8T6?

**Comment by der-pw** [comment]
> kann man für den EPROM auch einen anderen benutzen? Denn den gibt es beim Conrad, RS, Reichelt nicht. Hättest du du ein alternative EMPROM?  

diesen von ST solltest du nehmen können
https://www.reichelt.de/eeprom-32-kb-4k-x-8-i2c-400-khz-2-5--5-5-v-so-8-st-24c32-mn6-p33376.html

> -Der DS18B20 wird der auch ausgelesen und von der Homematic Oberfläche angezeigt?  

nein, er ist nur für die interne Schutzabschaltung


> -J2 und J3: benötigt man für was genau? Denke nicht das die für den Dimmer nötwenig sind

J2 ist der Terminalanschluss für LED1, musst du wissen, wie du deine LED-Strip da verbindest
und J3 der Pinheader um einen Encoder anzuschließen.
Schätze mal, du meist J3 und J4. Die müssen nicht zwingend verwendet werden.

> U2 welchen Controller genau? STM32 F103C6T6 oder STM32 F103C8T6?  

Der Blue Pill hat einen STM32F103C8T6 drauf
